import React, { useState } from 'react';
import { 
  FileText, 
  Calendar, 
  Download, 
  Eye, 
  Share2, 
  ShieldAlert, 
  Plus, 
  CheckCircle2
} from 'lucide-react';
import { useCyber } from '../../context/CyberContext';
import { SecurityReport } from '../../types/cyber';
import { ReportViewer } from './ReportViewer';

export const ReportsView: React.FC = () => {
  const { reports, selectedReport, setSelectedReport, addToast } = useCyber();
  const [activeReport, setActiveReport] = useState<SecurityReport | null>(null);

  const handleExport = (repTitle: string) => {
    addToast('success', `Exporting report: ${repTitle}`);
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-y-auto bg-cyber-bg p-6 space-y-6 select-none">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <span>Security Reports & Documentation</span>
          </h2>
          <p className="text-xs text-cyber-muted">
            Enterprise security assessment reports generated by CyberAgents AI platform.
          </p>
        </div>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reports.map((rep) => (
          <div 
            key={rep.id}
            className="p-6 rounded-2xl bg-cyber-card border border-cyber-border hover:border-cyber-accent/40 shadow-cyber transition-all space-y-4 flex flex-col justify-between group"
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="px-2.5 py-0.5 rounded text-[10px] font-mono bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-semibold flex items-center gap-1.5">
                  <CheckCircle2 className="w-3 h-3" />
                  {rep.status}
                </span>

                <div className="flex items-center gap-1 text-[11px] text-cyber-muted font-mono">
                  <Calendar className="w-3.5 h-3.5 text-cyber-accent" />
                  <span>{rep.date}</span>
                </div>
              </div>

              <h3 className="text-base font-bold text-slate-100 group-hover:text-cyber-accent transition-colors">
                {rep.title}
              </h3>

              <p className="text-xs text-cyber-muted line-clamp-2 leading-relaxed">
                {rep.executiveSummary}
              </p>

              <div className="grid grid-cols-3 gap-2 pt-1 font-mono text-[11px]">
                <div className="bg-cyber-surface p-2 rounded-lg border border-cyber-border/60">
                  <span className="text-[10px] text-cyber-muted block">Risk Level</span>
                  <span className="font-bold text-rose-400">{rep.riskLevel} ({rep.riskScore})</span>
                </div>
                <div className="bg-cyber-surface p-2 rounded-lg border border-cyber-border/60">
                  <span className="text-[10px] text-cyber-muted block">Findings</span>
                  <span className="font-bold text-slate-200">{rep.findingsCount} Issues</span>
                </div>
                <div className="bg-cyber-surface p-2 rounded-lg border border-cyber-border/60">
                  <span className="text-[10px] text-cyber-muted block">Format</span>
                  <span className="font-bold text-cyber-cyan">PDF / MD</span>
                </div>
              </div>
            </div>

            {/* Action Bar */}
            <div className="pt-4 border-t border-cyber-border/60 flex items-center justify-between gap-2">
              <button
                onClick={() => setActiveReport(rep)}
                className="px-4 py-2 rounded-lg font-semibold text-xs text-white bg-cyber-accent hover:bg-indigo-600 shadow-glow-accent transition-all flex items-center gap-1.5"
              >
                <Eye className="w-3.5 h-3.5" />
                <span>View Full Report</span>
              </button>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleExport(rep.title)}
                  className="p-2 rounded-lg bg-cyber-surface border border-cyber-border text-cyber-muted hover:text-white transition-colors"
                  title="Export Report"
                >
                  <Download className="w-4 h-4" />
                </button>
                <button
                  onClick={() => addToast('info', 'Share link copied')}
                  className="p-2 rounded-lg bg-cyber-surface border border-cyber-border text-cyber-muted hover:text-white transition-colors"
                  title="Share Report"
                >
                  <Share2 className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Detailed Document Modal Viewer */}
      <ReportViewer 
        report={activeReport} 
        onClose={() => setActiveReport(null)} 
      />
    </div>
  );
};
